spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cccat15
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      jdbc:
        lob.non-contextual-creation: true
      hibernate:
        show_sql: true
