spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cccat15
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show_sql: true
    properties:
      jdbc:
        lob.non-contextual-creation: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
